name: chatsen_resources
description: Chatsen Resources
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  json_annotation: ^4.0.1
  http: any

dev_dependencies:
  lints: ^1.0.0
  json_serializable: ^4.1.3
  build_runner: ^2.0.4 # flutter pub run build_runner watch # or build
